// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SafariAPI;

namespace SafariAPI.Migrations
{
    [DbContext(typeof(SafariAPIContext))]
    partial class SafariAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SafariApi.Models.SeenAnimals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CountOfTimesSeen");

                    b.Property<string>("LocationOfLastSeen");

                    b.Property<string>("Species");

                    b.HasKey("Id");

                    b.ToTable("SeenAnimals");

                    b.HasData(
                        new { Id = -1, CountOfTimesSeen = 3, LocationOfLastSeen = "Umbrella Acacias", Species = "Springbok" },
                        new { Id = -2, CountOfTimesSeen = 5, LocationOfLastSeen = "Watering Hole", Species = "Spotted Hyena" },
                        new { Id = -3, CountOfTimesSeen = 6, LocationOfLastSeen = "Rock Outcrop", Species = "Meerkat" },
                        new { Id = -4, CountOfTimesSeen = 1, LocationOfLastSeen = "Termite Mound", Species = "Aardvark" },
                        new { Id = -5, CountOfTimesSeen = 3, LocationOfLastSeen = "Watering Hole", Species = "Wildebeest" },
                        new { Id = -6, CountOfTimesSeen = 2, LocationOfLastSeen = "Rock Outcrop", Species = "African Rock Python" },
                        new { Id = -7, CountOfTimesSeen = 4, LocationOfLastSeen = "Umbrella Acacias", Species = "Grant's Gazelle" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
